/*
 * generated by Xtext
 */
package pl.zgora.jug.xtext;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class DemoDslStandaloneSetup extends DemoDslStandaloneSetupGenerated{

	public static void doSetup() {
		new DemoDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

