/*
 * generated by Xtext
 */
package pl.zgora.jug.xtext;

import org.eclipse.xtext.conversion.IValueConverterService;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class DemoDslRuntimeModule extends pl.zgora.jug.xtext.AbstractDemoDslRuntimeModule {

	@Override
	public Class<? extends IValueConverterService> bindIValueConverterService() {
		return DemoIValueConverterService.class;
	}

}
