/*
 * generated by Xtext
 */
package pl.zgora.jug.xtext.ui;

import org.eclipse.jface.viewers.ILabelProvider;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.contentassist.ContentProposalLabelProvider;

import com.google.inject.Binder;

import pl.zgora.jug.xtext.ui.labeling.DemoDslLabelProvider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DemoDslUiModule extends pl.zgora.jug.xtext.ui.AbstractDemoDslUiModule {
	public DemoDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	@Override
	public void configureContentProposalLabelProvider(Binder binder) {
		binder.bind(ILabelProvider.class).annotatedWith(ContentProposalLabelProvider.class)
				.to(DemoDslLabelProvider.class);
	}
}
