/*
 * generated by Xtext
 */
package pl.zgora.jug.xtext.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import pl.zgora.jug.xtext.services.DemoDslGrammarAccess;

public class DemoDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private DemoDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected pl.zgora.jug.xtext.parser.antlr.internal.InternalDemoDslParser createParser(XtextTokenStream stream) {
		return new pl.zgora.jug.xtext.parser.antlr.internal.InternalDemoDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "LoggerConfig";
	}
	
	public DemoDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(DemoDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
