/*
 * generated by Xtext
 */
package pl.zgora.jug.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DemoDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("pl/zgora/jug/xtext/parser/antlr/internal/InternalDemoDsl.tokens");
	}
}
