/*
 * generated by Xtext
 */
package pl.zgora.jug.xtext;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class DemoDslUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return pl.zgora.jug.xtext.ui.internal.DemoDslActivator.getInstance().getInjector("pl.zgora.jug.xtext.DemoDsl");
	}
	
}
